# Utiliser une image Node.js 18 Alpine comme base
FROM node:18-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier tous les fichiers du projet
COPY . .

# Installer les dépendances
RUN npm install

# Exposer le port 8000
EXPOSE 8000

# Commande de démarrage
CMD ["npm", "run", "dev"]
