

services:
  postgres:
    image: postgres:16
    container_name: candidater-en-france-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PROD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      POSTGRES_DB: ${POSTGRES_DB_PROD}

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: candidater-en-france-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER_PROD}:${POSTGRES_PASSWORD_PROD}@postgres:5432/${POSTGRES_DB_PROD}
      PORT: 3000
      RESET_SECRET: ${RESET_SECRET_PROD}
      NODE_ENV: production
      # Database connection variables that the backend code expects
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER_PROD}
      DB_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      DB_NAME: ${POSTGRES_DB_PROD}
    command: ["sh", "-c", "sleep 10 && node index.js"]
    volumes:
      # Partage le dossier backup pour que le script de seeding puisse trouver le fichier JSON
      - ./backup:/app/backup
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_URL=http://localhost:3000/api
    container_name: candidater-en-france-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8000:8000"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    networks:
      - app-network
    command: serve -s dist -l 8000
    # volumes: # Désactivé pour la prod
    #   - ./src/client:/app/src/client

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
