version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: candidater-en-france-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PROD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      POSTGRES_DB: ${POSTGRES_DB_PROD}

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: candidater-en-france-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER_PROD}:${POSTGRES_PASSWORD_PROD}@postgres:5432/${POSTGRES_DB_PROD}
      PORT: 3000
      RESET_SECRET: ${RESET_SECRET_PROD}
      NODE_ENV: production
      POSTGRES_HOST: postgres
    # volumes: # Désactivé pour la prod, le code est dans l'image
    #   - ./src/server:/app/src/server
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: candidater-en-france-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: serve -s dist -l 8000
    # volumes: # Désactivé pour la prod
    #   - ./src/client:/app/src/client

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
