# Utiliser une image Node.js légère comme base
FROM node:18-alpine

# Définir le répertoire de travail
WORKDIR /app/src/server

# Copier les fichiers de dépendances du serveur
COPY src/server/package.json ./
COPY src/server/package-lock.json ./

# Installer les dépendances du serveur
RUN npm install
RUN npm install multer

# Copier le reste du code du serveur
COPY src/server/ .

# Exposer le port
EXPOSE 3000

# Commande de démarrage
CMD ["node", "index.js"]
