export enum StageType {
  INITIAL_CONTACT = 'INITIAL_CONTACT',
  SCREENING = 'SCREENING', 
  TECHNICAL_INTERVIEW = 'TECHNICAL_INTERVIEW',
  HR_INTERVIEW = 'HR_INTERVIEW',
  FINAL_INTERVIEW = 'FINAL_INTERVIEW',
  OFFER = 'OFFER',
  HIRED = 'HIRED',
  REJECTED = 'REJECTED'
}

export enum CandidateStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  HIRED = 'HIRED', 
  REJECTED = 'REJECTED',
  PENDING = 'PENDING'
}
